using System;
using System.ComponentModel.DataAnnotations;

namespace Viv2.API.Core.Entities
{
 
    /// <summary>
    /// A refresh token, as handed around by Core.
    ///
    /// As per AccessToken, this model does not represent the actual claims as generated by the active TokenMinter,
    /// rather it contains extra information such as the encoded value of the minted token, and some information
    /// pertinent to the use of the token.
    /// </summary>
    public class RefreshToken
    {
        /// <summary>
        /// The encoded refresh token as given by the minter.
        /// </summary>
        [Key]
        public string Token { get; init; }
        
        /// <summary>
        /// Hostname of the entity that issued the refresh token. (for book keeping purposes)
        /// </summary>
        public string IssuedBy { get; init; }
        
        /// <summary>
        /// The ID of the user to which the refresh token was minted.
        /// </summary>
        public Guid IssuedTo { get; init; }
        
        /// <summary>
        /// When (seconds since unix epoch) the refresh token expires.
        /// </summary>
        /// <returns></returns>
        public DateTime ExpiresAt { get; init; }
    }
}
